# Generated by Django 6.0.2 on 2026-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('leader', models.CharField(max_length=100, verbose_name='Бригадир')),
                ('is_working', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='RefrigerationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('temperature', models.FloatField(default=0, verbose_name='Температура')),
                ('pressure', models.FloatField(default=0, verbose_name='Давление')),
                ('status', models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('alarm', 'Авария')], default='normal', max_length=20, verbose_name='Статус')),
                ('pos_x', models.IntegerField(default=100, verbose_name='Позиция X')),
                ('pos_y', models.IntegerField(default=100, verbose_name='Позиция Y')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
