# Generated by Django 6.0.2 on 2026-04-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('leader', models.CharField(max_length=100, verbose_name='Бригадир')),
                ('is_working', models.BooleanField(default=True, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='RefrigerationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('element_type', models.CharField(choices=[('kp', 'Кристаллизатор'), ('compressor', 'Компрессор'), ('rd', 'Ресивер дренажный'), ('oz', 'Отделитель жидкости'), ('t', 'Теплообменник'), ('ps', 'Промышленный сосуд'), ('mo', 'Маслоотделитель'), ('avo', 'Аппарат воздушного охлаждения'), ('gl', 'Гаситель пульсаций'), ('ktv', 'Конденсатор'), ('rl', 'Ресивер линейный')], default='kp', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('normal', 'Норма'), ('warning', 'Предупреждение'), ('alarm', 'Авария')], default='normal', max_length=20, verbose_name='Статус')),
                ('temperature', models.FloatField(default=0, verbose_name='Температура сырья (°C)')),
                ('ammonia_temp', models.FloatField(default=0, verbose_name='Температура аммиака (°C)')),
                ('pressure', models.FloatField(default=0, verbose_name='Давление (бар)')),
                ('pos_x', models.IntegerField(default=100, verbose_name='Позиция X')),
                ('pos_y', models.IntegerField(default=100, verbose_name='Позиция Y')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('temperature_day', models.IntegerField(verbose_name='Температура днем')),
                ('temperature_night', models.IntegerField(verbose_name='Температура ночью')),
                ('condition', models.CharField(default='Ясно', max_length=50, verbose_name='Погода')),
                ('humidity', models.IntegerField(default=70, verbose_name='Влажность')),
                ('wind_speed', models.IntegerField(default=3, verbose_name='Ветер, м/с')),
                ('icon', models.CharField(default='☀️', max_length=20)),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогнозы погоды',
                'ordering': ['date'],
            },
        ),
    ]
