# Generated by Django 6.0.2 on 2026-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerationelement',
            name='element_type',
            field=models.CharField(choices=[('compressor', 'Компрессор'), ('evaporator', 'Испаритель'), ('condenser', 'Конденсатор'), ('sensor', 'Датчик'), ('valve', 'Клапан')], default='sensor', max_length=20, verbose_name='Тип'),
        ),
    ]
