# Generated by Django 6.0.2 on 2026-04-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refrigerationelement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={},
        ),
        migrations.AlterField(
            model_name='brigade',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='leader',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='ammonia_temp',
            field=models.FloatField(default=0, verbose_name='Температура аммиака'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='element_type',
            field=models.CharField(choices=[('kp', 'Кристаллизатор'), ('t', 'Теплообменник'), ('compressor', 'Компрессор'), ('rd', 'Ресивер дренажный'), ('oz', 'Отделитель жидкости'), ('ps', 'Промышленный сосуд'), ('mo', 'Маслоотделитель'), ('avo', 'АВО'), ('gl', 'Гаситель пульсаций'), ('ktv', 'Конденсатор'), ('rl', 'Ресивер линейный')], default='kp', max_length=20),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pressure',
            field=models.FloatField(default=0, verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='status',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Температура сырья'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='condition',
            field=models.CharField(default='Ясно', max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='humidity',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature_night',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_speed',
            field=models.IntegerField(default=3),
        ),
    ]
