# Generated by Django 6.0.2 on 2026-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brigade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerationelement',
            name='level',
            field=models.FloatField(default=50, verbose_name='Уровень (%)'),
        ),
    ]
