# Generated by Django 6.0.2 on 2026-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_refrigerationelement_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('temperature_day', models.IntegerField(verbose_name='Температура днем')),
                ('temperature_night', models.IntegerField(verbose_name='Температура ночью')),
                ('condition', models.CharField(default='Ясно', max_length=50, verbose_name='Погода')),
                ('humidity', models.IntegerField(default=70, verbose_name='Влажность')),
                ('wind_speed', models.IntegerField(default=3, verbose_name='Ветер, м/с')),
                ('icon', models.CharField(default='☀️', max_length=20)),
            ],
            options={
                'verbose_name': 'Прогноз погоды',
                'verbose_name_plural': 'Прогнозы погоды',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='element_type',
            field=models.CharField(choices=[('compressor', 'Компрессор'), ('evaporator', 'Испаритель'), ('condenser', 'Конденсатор'), ('sensor', 'Датчик'), ('vessel', 'Сосуд'), ('separator', 'Сепаратор'), ('receiver', 'Ресивер'), ('heat_exchanger', 'Теплообменник'), ('filter', 'Фильтр'), ('damper', 'Гаситель пульсаций'), ('oil_separator', 'Маслоотделитель')], default='sensor', max_length=20, verbose_name='Тип'),
        ),
    ]
