# Generated by Django 6.0.2 on 2026-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_refrigerationelement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerationelement',
            name='discharge_temp_stage1',
            field=models.FloatField(default=0, verbose_name='Температура нагнетания 1 ступени'),
        ),
        migrations.AddField(
            model_name='refrigerationelement',
            name='discharge_temp_stage2',
            field=models.FloatField(default=0, verbose_name='Температура нагнетания 2 ступени'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='element_type',
            field=models.CharField(choices=[('kp', 'Кристаллизатор'), ('t', 'Теплообменник'), ('compressor', 'Компрессор'), ('rd', 'Ресивер дренажный'), ('oz', 'Отделитель жидкости'), ('ps', 'Промышленный сосуд'), ('mo', 'Маслоотделитель'), ('avo', 'АВО'), ('gl', 'Гаситель пульсаций'), ('ktv', 'Конденсатор'), ('rl', 'Ресивер линейный'), ('ms', 'Маслосборник')], default='kp', max_length=20),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='status',
            field=models.CharField(choices=[('normal', '✅ В работе'), ('warning', '⚠️ Внимание'), ('alarm', '🔴 Авария'), ('stopped', '⏹️ Остановлен')], default='normal', max_length=20),
        ),
    ]
