# Generated by Django 6.0.2 on 2026-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weatherforecast_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refrigerationelement',
            options={'verbose_name': 'Элемент схемы', 'verbose_name_plural': 'Элементы схемы'},
        ),
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='element_type',
            field=models.CharField(choices=[('kp', 'Кристаллизатор'), ('compressor', 'Компрессор'), ('rd', 'Ресивер дренажный'), ('oz', 'Отделитель жидкости'), ('t', 'Теплообменник'), ('ps', 'Промышленный сосуд'), ('mo', 'Маслоотделитель'), ('avo', 'Аппарат воздушного охлаждения'), ('gl', 'Гаситель пульсаций'), ('ktv', 'Конденсатор'), ('rl', 'Ресивер линейный')], default='kp', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pos_x',
            field=models.IntegerField(default=0, verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pos_y',
            field=models.IntegerField(default=0, verbose_name='Координата Y'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='pressure',
            field=models.FloatField(default=0, verbose_name='Давление (бар)'),
        ),
        migrations.AlterField(
            model_name='refrigerationelement',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Температура (°C)'),
        ),
    ]
