# Generated by Django 6.0.2 on 2026-05-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_refrigerationelement_discharge_temp_stage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('oil_3', 'Масло 3 фракция'), ('oil_4', 'Масло 4 фракция'), ('oil_5', 'Масло 5 фракция'), ('paraffin', 'Парафин'), ('zvp', 'ЗВП (Застывающие вещества)')], max_length=100, unique=True, verbose_name='Тип сырья')),
                ('total_volume', models.FloatField(default=0, verbose_name='Общий объём (м³)')),
                ('current_volume', models.FloatField(default=0, verbose_name='Текущий остаток (м³)')),
                ('temperature_required', models.FloatField(default=-20, verbose_name='Требуемая температура (°C)')),
                ('freezing_point', models.FloatField(default=-10, verbose_name='Температура застывания (°C)')),
            ],
            options={
                'verbose_name': 'Тип сырья',
                'verbose_name_plural': 'Типы сырья',
            },
        ),
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={'ordering': ['date'], 'verbose_name': 'Прогноз погоды', 'verbose_name_plural': 'Прогнозы погоды'},
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='condition',
            field=models.CharField(default='Ясно', max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='humidity',
            field=models.IntegerField(default=70, verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='icon',
            field=models.CharField(default='☀️', max_length=20, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature_day',
            field=models.IntegerField(verbose_name='Температура днём (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='temperature_night',
            field=models.IntegerField(verbose_name='Температура ночью (°C)'),
        ),
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind_speed',
            field=models.IntegerField(default=3, verbose_name='Ветер (м/с)'),
        ),
        migrations.CreateModel(
            name='RawMaterialLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(verbose_name='Объём (м³)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('planned', '📋 Запланирована'), ('in_progress', '🔄 В процессе'), ('completed', '✅ Завершена'), ('cancelled', '❌ Отменена')], default='planned', max_length=20, verbose_name='Статус')),
                ('operator', models.CharField(blank=True, default='', max_length=100, verbose_name='Оператор')),
                ('note', models.TextField(blank=True, default='', max_length=500, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rawmaterial', verbose_name='Тип сырья')),
            ],
            options={
                'verbose_name': 'Загрузка сырья',
                'verbose_name_plural': 'Загрузки сырья',
                'ordering': ['-created_at'],
            },
        ),
    ]
