# Generated by Django 6.0.2 on 2026-05-03 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rawmaterial_alter_weatherforecast_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_from', models.CharField(choices=[('chief', 'Начальник установки'), ('deputy', 'Зам. начальника'), ('mechanic', 'Механик установки')], max_length=20, verbose_name='От кого')),
                ('description', models.TextField(verbose_name='Содержание распоряжения')),
                ('status', models.CharField(choices=[('active', '📋 Действующее'), ('in_progress', '🔄 Выполняется'), ('completed', '✅ Выполнено'), ('cancelled', '❌ Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Распоряжение',
                'verbose_name_plural': 'Распоряжения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(verbose_name='Время с')),
                ('time_to', models.TimeField(verbose_name='Время по')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Запись вахтового журнала',
                'verbose_name_plural': 'Вахтовый журнал',
                'ordering': ['-date', '-time_from'],
            },
        ),
    ]
