# Generated by Django 6.0.2 on 2026-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_shiftlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='name',
        ),
        migrations.AddField(
            model_name='brigade',
            name='driver',
            field=models.CharField(default='', max_length=100, verbose_name='Машинист холодильного отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='filter_operator',
            field=models.CharField(default='', max_length=100, verbose_name='Оператор фильтровального отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='number',
            field=models.CharField(choices=[('1', 'Бригада №1'), ('2', 'Бригада №2'), ('3', 'Бригада №3'), ('4', 'Бригада №4')], default='1', max_length=1, unique=True, verbose_name='Номер бригады'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='pump_operator',
            field=models.CharField(default='', max_length=100, verbose_name='Оператор насосного отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='regen_operator',
            field=models.CharField(default='', max_length=100, verbose_name='Оператор регенеративного отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='shift_end',
            field=models.TimeField(default='20:00', verbose_name='Конец смены'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='shift_start',
            field=models.TimeField(default='08:00', verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='На смене'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='leader',
            field=models.CharField(default='', max_length=100, verbose_name='Старший оператор'),
        ),
    ]
