# Generated by Django 6.0.2 on 2026-05-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_brigade_options_remove_brigade_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('senior_operator', 'Старший оператор'), ('refrigeration_operator', 'Машинист холодильного отделения'), ('pump_operator', 'Оператор насосного отделения'), ('regeneration_operator', 'Оператор регенеративного отделения'), ('filter_operator', 'Оператор фильтровального отделения')], max_length=30, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='regen_operator',
        ),
        migrations.AddField(
            model_name='brigade',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brigade',
            name='is_working',
            field=models.BooleanField(default=True, verbose_name='Работает сейчас'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер бригады'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(choices=[('oil_3', 'Масло 3 фракция'), ('oil_4', 'Масло 4 фракция'), ('oil_5', 'Масло 5 фракция'), ('paraffin', 'Парафин'), ('zvp', 'ЗВП')], max_length=100, unique=True, verbose_name='Тип сырья'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='refrigeration_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrigeration_brigade', to='main.employee', verbose_name='Машинист холодильного отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='regeneration_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regeneration_brigade', to='main.employee', verbose_name='Оператор регенеративного отделения'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='senior_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_brigade', to='main.employee', verbose_name='Старший оператор'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='filter_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_brigade', to='main.employee', verbose_name='Оператор фильтровального отделения'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='pump_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_brigade', to='main.employee', verbose_name='Оператор насосного отделения'),
        ),
    ]
