# Generated by Django 6.0.2 on 2026-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_remove_brigade_driver_remove_brigade_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brigade',
            name='filter_operator',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='pump_operator',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='regeneration_operator',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='senior_operator',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='refrigeration_operator',
        ),
        migrations.AlterModelOptions(
            name='brigade',
            options={},
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='number',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='shift_start',
        ),
        migrations.AddField(
            model_name='brigade',
            name='leader',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brigade',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(choices=[('oil_3', 'Масло 3 фракция'), ('oil_4', 'Масло 4 фракция'), ('oil_5', 'Масло 5 фракция'), ('paraffin', 'Парафин'), ('zvp', 'ЗВП (Застывающие вещества)')], max_length=100, unique=True, verbose_name='Тип сырья'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
